### PR TITLE
Keep unused buffers associated with their layer

### PR DESCRIPTION
**Pull request by mrobinson**
This prevents sending back unused buffers to the wrong pipeline in
Servo, which could potentially lead to problems at another time. Instead
keep buffers associated with their layer and let the client handle
sending them back.

### CODE REVIEW

**Comment by Ms2ger** [comment]
@glennw: what's the story here?

**Comment by glennw** [comment]
r+

(I'll leave @mrobinson to merge this when ready).

**Comment by mrobinson** [comment]
Thanks for the review. I'll have the corresponding Servo patch ready to roll on Monday.

**Comment by mbrubeck** [comment]
CC servo/servo#4895

**Pull request merged**
