### PR TITLE
Do not allow the backing IOSurface to change underneath a NativeSurface.

### PR DESCRIPTION
**Pull request by notriddle**
Mac has been observed to give out two IOSurfaces with the same ID to a
single compositor process, after it allocates the first, hands it to the
paint process, releases its hold on the first, allocates the second,
then hands the second over to the paint process. Doing that sequence,
unsurprisingly, can screw things up royally.

Fixes the Mac-specific bug blocking servo/servo#8641

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/228)

### CODE REVIEW

**Comment by notriddle** [comment]
Sorry about the flood of tweaks. Forgot to remove println's, which called cgl functions that I had added for debugging.

This version, in addition to compiling in CI, passes wpt with stock cgl-rs.

**Comment by glennw** [comment]
I have very little experience with mac specific graphics things - probably best for @pcwalton to check this over.

**Comment by jdm** [comment]
Bah, aster is busted on nightly again :(

**Comment by jdm** [comment]
Bah. It's hard to say what's dragging in aster, but it seems to be pinned to 0.11 somehow even though 0.12 has been released that addresses this :(

**Pull request merged**
