### PR TITLE
Specify license in Cargo.toml

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/227)

### CODE REVIEW

**Comment by notriddle** [comment]
We're going to need all the contributors to consent to the relicense (I'm fine with it, BTW).

**Comment by frewsxcv** [comment]
The license files already existed in the root directory, the cargo metadata just wasn't there, so I don't think it's really a relicense

**Comment by notriddle** [comment]
Okay, I didn't notice it. Thanks!

**Pull request merged**
