### PR TITLE
Allow NativeSurface cloning

### PR DESCRIPTION
**Pull request by ecoal95**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/160)

### CODE REVIEW

**Comment by ecoal95** [comment]
Something about this @pcwalton? I need it for sending surfaces from the WebGL task.

**Comment by jdm** [comment]
@ecoal95 Am I right in assuming that this isn't necessary any more?

**Comment by mrobinson** [comment]
Maybe @ecoal95 and I can coordinate to figure out a way to do this.

**Comment by ecoal95** [comment]
I currently have no access to a computer until day 20 approx., but that would be great @mrobinson :)

**Comment by metajack** [comment]
@ecoal95 @mrobinson Did this get resolved?

**Comment by mrobinson** [comment]
Cloning probably isn't going to work for all circumstances, since NativeSurfaces can be backed by memory. I wonder if we should save this for later, since WebRender might dramatically change how we implement this. @ecoal95 What do you think?

**Comment by ecoal95** [comment]
Yes, totally agree, I hadn't thought about memory backed surfaces.

I exchanged some emails with @glennw about possible WebRender implementations, if you're interested I can try to organize them and create a meta-issue in glennw/webrender about that.

Closing this for now then :P

**Comment by mrobinson** [comment]
@ecoal95 Yes, that would be great!

**Pull request closed without merging**
