### PR TITLE
Increment version number.

### PR DESCRIPTION
**Pull request by notriddle**
(this will need to be pushed to Crates.IO, of course)

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/231)

### CODE REVIEW

**Comment by jdm** [comment]
It's not published on crates.io, so you're good to go.

**Comment by notriddle** [comment]
Not?

**Comment by jdm** [comment]
Yes. rust-layers is not published on crates.io since it has non-crates deps.

**Comment by notriddle** [comment]
OK

**Pull request merged**
