### PR TITLE
Bump cargo

### PR DESCRIPTION
**Pull request by Manishearth**
Forgot to do this when I added the plugins feature

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/214)

### CODE REVIEW

**Comment by Manishearth** [comment]
@larsbergstrom libcpocalypse :/

**Comment by Manishearth** [comment]
@bors-servo retry
oops

**Comment by jdm** [comment]
x11-rs problems due to conflicting libc.

**Comment by larsbergstrom** [comment]
@bors-servo retry

Should go through, now that #215 landed.

**Pull request merged**
