### PR TITLE
armv7 support

### PR DESCRIPTION
**Pull request by fabricedesre**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-layers/234)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Ugh https://github.com/serde-rs/quasi/issues/35

**Comment by fabricedesre** [comment]
Not sure what's going on with the appveyor failure... any idea @frewsxcv ?

**Comment by frewsxcv** [comment]
I'm not too familiar with Appveyor. I'm going to cc @larsbergstrom since they have more experienced with Appveyor and Windows in general.

**Comment by fabricedesre** [comment]
Well it seems that appveyor was never really set up properly. See for instance the same failure in https://github.com/servo/rust-layers/pull/235 that landed.

**Comment by jdm** [comment]
Oh yeah, I stalled on https://github.com/servo/rust-layers/pull/230. I'll turn it off.

**Comment by fabricedesre** [comment]
@jdm so woh can review this one?

**Comment by larsbergstrom** [comment]
I'm fine with this if you squash.

@bors-servo delegate+

**Pull request merged**
