### PR TITLE
Add aarch64-unknown-linux-gnu dependencies

### PR DESCRIPTION
**Pull request by akiss77**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/196)

### CODE REVIEW

**Comment by jdm** [comment]
Huh, what happened to bors here?

**Comment by metajack** [comment]
Checking. My first thought was that travis wasn't notifying, but that seems to be set up right.

**Comment by metajack** [comment]
It appears we hit a rate limit. No idea why :(

```
Starting build of servo/rust-layers#196 on auto: e08248406be52ba493b193671579371e9993d181
INFO:homu:Starting build of servo/rust-layers#196 on auto: e08248406be52ba493b193671579371e9993d181
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/homu/server.py", line 533, in travis
    report_build_res(succ, info['build_url'], 'travis', repo_label, state, logger)
  File "/home/servo/homu/homu/server.py", line 360, in report_build_res
    utils.github_create_status(state.get_repo(), state.head_sha, 'success', url, desc, context='homu')
  File "/home/servo/homu/homu/utils.py", line 33, in github_create_status
    js = repo._json(repo._post(url, data=data), 201)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 API rate limit exceeded for bors-servo.
Traceback (most recent call last):
  File "/home/servo/homu/homu/main.py", line 481, in fetch_mergeability
    mergeable = state.get_repo().pull_request(state.num).mergeable
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/repos/repo.py", line 1683, in pull_request
    json = self._json(self._get(url), 200)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 API rate limit exceeded for bors-servo.
Traceback (most recent call last):
  File "/home/servo/homu/homu/main.py", line 481, in fetch_mergeability
    mergeable = state.get_repo().pull_request(state.num).mergeable
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/repos/repo.py", line 1683, in pull_request
    json = self._json(self._get(url), 200)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 API rate limit exceeded for bors-servo.
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/homu/server.py", line 321, in github
    realtime=True,
  File "/home/servo/homu/homu/main.py", line 237, in parse_commands
    state.add_comment(':pushpin: Commit {:.7} has been approved by `{}`\n\n<!-- @{} r={} {} -->'.format(state.head_sha, approver, my_username, approver, state.head_sha))
  File "/home/servo/homu/homu/main.py", line 111, in add_comment
    issue = self.issue = self.get_repo().issue(self.num)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/repos/repo.py", line 1020, in issue
    json = self._json(self._get(url), 200)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 API rate limit exceeded for bors-servo.
```

**Comment by metajack** [comment]
@barosl Any ideas about that?

**Pull request merged**
