### PR TITLE
M1506 : Refactor GLES2

### PR DESCRIPTION
**Pull request by prashantgupta24**
Added a flag to RenderContext::new in rendergl.rs, this is in reference to adding a new command-line option to allow selecting the graphics backend (GL or ES2). Also created an enum for graphics select options.

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/213)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Could you combine this and #212 into a single pull request, please?  It looks like you could squash all of these commits and all of the commits in #212 into a single commit, then force-push that commit to one of your branches, and close the other PR.

**Comment by mbrubeck** [comment]
Sorry, I got confused.  Please ignore my previous comment.

**Comment by mbrubeck** [comment]
Thanks for the PR! I have some minor style suggestions below...


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/rendergl.rs, line 466 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1uf_8Sup8dEcgA0dto)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L466)):</sup>
Please make this type `pub` so it can be used in the `new` function (see comment below).


---

<sup>**[src/rendergl.rs, line 469 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1ufUAFSSowXyx8XVIm)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L469)):</sup>
nit: please remove the leading spaces here


---

<sup>**[src/rendergl.rs, line 491 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1uf-FUqwRpk9N9WWkn)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L491)):</sup>
Could you make this take a `GraphicOption` instead of a `bool`?


---

<sup>**[src/rendergl.rs, line 495 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1ufgZ6OgmwyU17YkHp)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L495)):</sup>
nit: No need to add extra blank lines in this function.


---

<sup>**[src/rendergl.rs, line 500 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1uf6VFKdoV_s3LPkgz)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L500)):</sup>
nit: These lines should use spaces instead of tabs for indentation, and opening braces (`{`) should not go on a new line.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-layers/213)

**Comment by Manishearth** [comment]
Why did the file mode change?

**Comment by Manishearth** [comment]
Oh, that was supposed to happen.

**Comment by Manishearth** [comment]
Could you change the mode for lib.rs and scene.rs as well? `chmod a-x src/*rs`

**Comment by mbrubeck** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[src/rendergl.rs, line 507 \[r1\]](https://reviewable.io:443/reviews/servo/rust-layers/213#-K1uhZKlQ_ufrUStXcTz)** ([raw file](https://github.com/servo/rust-layers/blob/a0f60d222e9e3bcf36d6d349c93fc113c9bc28df/src/rendergl.rs#L507)):</sup>
It looks like the `graphics_select` variable is unused.  Is there another patch coming that uses this variable to change the graphics back-end?  We should wait to until that change is ready, and land them together.  (Otherwise it will generate compiler warnings.)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-layers/213)

**Comment by jdm** [comment]
@mbrubeck I would prefer for this to merge with a _ prefix; it's easier for [project evaluation](https://github.com/servo/servo/wiki/Refactor-GLES2-student-project) purposes if these changes can merge sooner.

**Comment by jdm** [comment]
Given https://github.com/servo/servo/pull/8869/ I don't believe this PR is necessary any longer.

**Pull request closed without merging**
