### PR TITLE
Replace deprecated Matrix4 with Matrix4D

### PR DESCRIPTION
**Pull request by UK992**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-layers/235)

### CODE REVIEW

**Comment by metajack** [comment]
This looks like it failed on serde/aster/quasi stuff when the plugins feature is enabled. Perhaps the version requirements need to be adjusted in Cargo.toml?

**Comment by UK992** [comment]
I think fix for this is in https://github.com/servo/ipc-channel/pull/68#issuecomment-216120756.

**Comment by metajack** [comment]
Ok. We can retry once that lands.

r=me when that happens.

**Comment by UK992** [comment]
Building is fixed now.

**Pull request merged**
