### PR TITLE
Remove `mark_tiles_outside_of_rect_as_unused`.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @glennw

### CODE REVIEW

**Comment by pcwalton** [comment]
It has the effect of removing all tiles outside the dirty rect, which
prevents us from invalidating portions of layers.

I tested the reftests and WPT tests with this and found no failures.

**Comment by mrobinson** [comment]
Doesn't this mean that all tiles in a layer are maintained until the layer is destroyed?

**Comment by pcwalton** [comment]
Doh! Yes, of course. The real solution here will be to use the viewport rect, not the dirty rect, to determine which tiles to throw out.

**Comment by pcwalton** [comment]
Boy, I feel silly now. :)

**Pull request merged**
