### PR TITLE
Init basic README with links to docs

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/205)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-layers/205)

**Comment by frewsxcv** [comment]
https://github.com/serde-rs/aster/issues/27

**Comment by frewsxcv** [comment]
serde-rs/aster#27 has been fixed. Can I get a retry?

**Pull request merged**
