### PR TITLE
Add travis config

### LINKED ISSUE #172: Build on travis-ci
Multi-OS support is not public on Travis, so we'd be limited to linux. That said, I think it's better than nothing; it would have prevented https://github.com/servo/rust-layers/pull/171

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #172

### CODE REVIEW

**Comment by metajack** [comment]
r=me if this works.

**Comment by metajack** [comment]
`error: unrecognized command line option ‘-std=gnu++11’`

**Comment by frewsxcv** [comment]
I'm not familiar with the build process to know of an immediate fix, so if you have any insight, let me know

**Comment by Ms2ger** [comment]
Sounds like the compiler on the travis container is too old?

**Comment by frewsxcv** [comment]
Relevant thread:

https://github.com/sass/node-sass/issues/483

Potentially relevant answer:

https://github.com/sass/node-sass/issues/483#issuecomment-60511404

**Comment by frewsxcv** [comment]
Tests pass now. r?

**Pull request merged**
