### PR TITLE
Refactor gle3

### PR DESCRIPTION
**Pull request by R00ney**
refactored  platform/surface.rs,   linux/surface.rs,  and created  egl/surface.rs   to  allow   linux to render on GL(GLX) or ES2(GLE).

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-layers/219)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/platform/egl/surface.rs, line 17 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dk2XhvXB2_XAO46zJ:-K4dk2XhvXB2_XAO46zK:-1417843189) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L17)):*
We can remove these commented out symbols

---

*[src/platform/egl/surface.rs, line 76 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkX13HzQkAo8rA3wg:-K4dkX13HzQkAo8rA3wh:738863597) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L76)):*
Since BGRA doesn't exist on Android, we'll need to use a cfg() flag to define a constant to the right value depending on platform - see https://github.com/glennw/webrender/blob/master/src/device.rs#L22 for an example of this.

---

*[src/platform/egl/surface.rs, line 86 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkE1_Dnqsin3NcqFI:-K4dkE1_Dnqsin3NcqFJ:485768097) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L86)):*
Fix indentation here, and update the comment to something like "TODO: Support GPU rasterizer path on EGL"

---

*[src/platform/egl/surface.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkgwd0tk1Wj88W4rD:-K4dkgwd0tk1Wj88W4rE:-1235489967) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L117)):*
Similar to above, let's make this "TODO: Support GPU rendering path on Android"

---

*[src/platform/egl/surface.rs, line 137 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkpFzY5dfVqUvy8oB:-K4dkpFzY5dfVqUvy8oC:993383584) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L137)):*
Let's comment the whole function out, and panic with something like "TODO: Support GL context on EGL"

---

*[src/platform/linux/surface.rs, line 14 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dl4dYrixvfLGBsftj:-K4dl4dYrixvfLGBsftk:581959291) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L14)):*
Add a comment here, something like "TODO: Linking EGL here is probably wrong - should it be done in gleam / glutin etc?"

---

*[src/platform/linux/surface.rs, line 15 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dl3WbLi1N74JnLoF9:-K4dl3WbLi1N74JnLoFA:-822219143) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L15)):*
Fix indentation

---

*[src/platform/surface.rs, line 35 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dlMPnFqiqx13tbBfo:-K4dlMPnFqiqx13tbBfp:2100852748) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/surface.rs#L35)):*
We'll still need the below code for android:

#[cfg(target_os="android")]
pub use platform::android::surface::NativeDisplay;

Added in addition to the change above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-layers/219)*

**Comment by glennw** [comment]
@mrobinson This is the main ES2 on Linux support from the NCSU students. It wasn't a huge amount of code in the end. I've done a quick initial review, but it would be good if you could take a look over it too.

**Comment by mrobinson** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[src/platform/egl/surface.rs, line 1 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gJB-QpNy02YGrZvpO:-K4gJB-QpNy02YGrZvpP:-726806022) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L1)):*
I think the year should be 2015 here.

---

*[src/platform/egl/surface.rs, line 26 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gKXkSIiWxkL-vayH1:-K4gKXkSIiWxkL-vayH2:1690462476) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L26)):*
Nit: You have an extra newline here.

---

*[src/platform/egl/surface.rs, line 87 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gKfrO7iRJyyAZ7qcD:-K4gKfrO7iRJyyAZ7qcE:-1929513711) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L87)):*
You can also remove this line.

---

*[src/platform/egl/surface.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkgwd0tk1Wj88W4rD:-K4gFo8WOl6PC6f5RW6Y:1522864651) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L117)):*
Also, best to remove commented out code here, like in the other sections of the file.

---

*[src/platform/egl/surface.rs, line 137 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4dkpFzY5dfVqUvy8oB:-K4gJeYzOM1dtBXPM74s:1703793637) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/egl/surface.rs#L137)):*
It's probably okay to remove all the code in this method and leave a panic.

---

*[src/platform/linux/surface.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gLMo6uoIIkDGlZVPH:-K4gLMo6uoIIkDGlZVPI:-2468293) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L44)):*
This should be called GLXDisplayInfo.

---

*[src/platform/linux/surface.rs, line 50 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gLPi4KH_P47R2iqPD:-K4gLPi4KH_P47R2iqPE:-1359735792) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L50)):*
Similarly, this should be called EGLDisplayInfo.

---

*[src/platform/linux/surface.rs, line 57 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gLSqcURstUrcbH32N:-K4gLSqcURstUrcbH32O:-1735736289) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L57)):*
EGL and GLX.

---

*[src/platform/linux/surface.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gM60b_coqRMIojGPa:-K4gM60b_coqRMIojGPb:-542013630) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L166)):*
The indentation is a bit off here. It should be indented 4 more spaces.

---

*[src/platform/linux/surface.rs, line 170 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gLZbBRxZrYIrx_ZDb:-K4gLZbBRxZrYIrx_ZDc:-6475422) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L170)):*
You can omit the curly brackets here and just make this:
```
NativeDisplay::EGL(_) => unreachable(),
```

---

*[src/platform/linux/surface.rs, line 175 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gLzZWeOFJ-Mb6z1IB:-K4gLzZWeOFJ-Mb6z1IC:-2011905514) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/linux/surface.rs#L175)):*
EGL and GLES2 are two separate concepts, so theoretically this should be called new_egl() or something like that. Also, this should probably be calling eglGetDisplay(info.display) instead of simply getting the current display.

---

*[src/platform/surface.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/rust-layers/219#-K4gQW0q7xCovH1LWRpk:-K4gQW0q7xCovH1LWRpl:1883602420) ([raw file](https://github.com/servo/rust-layers/blob/5b3363f56b7900c6b94e5afce0239f960814c518/src/platform/surface.rs#L56)):*
Nit: missing a space after the ```display,``` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-layers/219)*

**Comment by mrobinson** [comment]
The changes look pretty reasonable to me, but I don't really understand the branch name. When you say gle3, do you mean OpenGLES3? Perhaps name it something like "First steps to allowing Linux to use EGL and OpenGLES3?"

**Comment by R00ney** [comment]
Closing for new PR

**Pull request closed without merging**
