### PR TITLE
Enable OSX support in travis config

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I acknowledge this is not working right now; I'll get around to fixing this sometime soon

**Comment by metajack** [comment]
@frewsxcv Can you add the exclusion for the master branch to this? Also what do you mean it's not working? Seems to have passed travis.

**Comment by frewsxcv** [comment]
> Can you add the exclusion for the master branch to this?

Done

>  Also what do you mean it's not working? 

My first couple attempts failed because of using `apt-get` on OSX, but I eventually added in the conditionals to each line in `before_install`. I meant to comment that it should be working now but GitHub was having issues at the time. This should be ready to go now

**Pull request merged**
